// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: heya/tokenfactory/v1/genesis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DenomAuthority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Admin         string                 `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenomAuthority) Reset() {
	*x = DenomAuthority{}
	mi := &file_heya_tokenfactory_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenomAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenomAuthority) ProtoMessage() {}

func (x *DenomAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenomAuthority.ProtoReflect.Descriptor instead.
func (*DenomAuthority) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *DenomAuthority) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *DenomAuthority) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

type GenesisState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DenomCreationFee string                 `protobuf:"bytes,1,opt,name=denom_creation_fee,json=denomCreationFee,proto3" json:"denom_creation_fee,omitempty"`
	Denoms           []*DenomAuthority      `protobuf:"bytes,2,rep,name=denoms,proto3" json:"denoms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_heya_tokenfactory_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisState) GetDenomCreationFee() string {
	if x != nil {
		return x.DenomCreationFee
	}
	return ""
}

func (x *GenesisState) GetDenoms() []*DenomAuthority {
	if x != nil {
		return x.Denoms
	}
	return nil
}

var File_heya_tokenfactory_v1_genesis_proto protoreflect.FileDescriptor

const file_heya_tokenfactory_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"\"heya/tokenfactory/v1/genesis.proto\x12\x14heya.tokenfactory.v1\"<\n" +
	"\x0eDenomAuthority\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12\x14\n" +
	"\x05admin\x18\x02 \x01(\tR\x05admin\"z\n" +
	"\fGenesisState\x12,\n" +
	"\x12denom_creation_fee\x18\x01 \x01(\tR\x10denomCreationFee\x12<\n" +
	"\x06denoms\x18\x02 \x03(\v2$.heya.tokenfactory.v1.DenomAuthorityR\x06denomsB\xc4\x01\n" +
	"\x18com.heya.tokenfactory.v1B\fGenesisProtoP\x01Z(heya/heya/tokenfactory/v1;tokenfactoryv1\xa2\x02\x03HTX\xaa\x02\x14Heya.Tokenfactory.V1\xca\x02\x14Heya\\Tokenfactory\\V1\xe2\x02 Heya\\Tokenfactory\\V1\\GPBMetadata\xea\x02\x16Heya::Tokenfactory::V1b\x06proto3"

var (
	file_heya_tokenfactory_v1_genesis_proto_rawDescOnce sync.Once
	file_heya_tokenfactory_v1_genesis_proto_rawDescData []byte
)

func file_heya_tokenfactory_v1_genesis_proto_rawDescGZIP() []byte {
	file_heya_tokenfactory_v1_genesis_proto_rawDescOnce.Do(func() {
		file_heya_tokenfactory_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_genesis_proto_rawDesc), len(file_heya_tokenfactory_v1_genesis_proto_rawDesc)))
	})
	return file_heya_tokenfactory_v1_genesis_proto_rawDescData
}

var file_heya_tokenfactory_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heya_tokenfactory_v1_genesis_proto_goTypes = []any{
	(*DenomAuthority)(nil), // 0: heya.tokenfactory.v1.DenomAuthority
	(*GenesisState)(nil),   // 1: heya.tokenfactory.v1.GenesisState
}
var file_heya_tokenfactory_v1_genesis_proto_depIdxs = []int32{
	0, // 0: heya.tokenfactory.v1.GenesisState.denoms:type_name -> heya.tokenfactory.v1.DenomAuthority
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_heya_tokenfactory_v1_genesis_proto_init() }
func file_heya_tokenfactory_v1_genesis_proto_init() {
	if File_heya_tokenfactory_v1_genesis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_genesis_proto_rawDesc), len(file_heya_tokenfactory_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heya_tokenfactory_v1_genesis_proto_goTypes,
		DependencyIndexes: file_heya_tokenfactory_v1_genesis_proto_depIdxs,
		MessageInfos:      file_heya_tokenfactory_v1_genesis_proto_msgTypes,
	}.Build()
	File_heya_tokenfactory_v1_genesis_proto = out.File
	file_heya_tokenfactory_v1_genesis_proto_goTypes = nil
	file_heya_tokenfactory_v1_genesis_proto_depIdxs = nil
}
