// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: heya/tokenfactory/v1/tx.proto

package types

import (
	_ "cosmossdk.io/api/cosmos/msg/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgCreateDenom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Subdenom      string                 `protobuf:"bytes,2,opt,name=subdenom,proto3" json:"subdenom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateDenom) Reset() {
	*x = MsgCreateDenom{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateDenom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateDenom) ProtoMessage() {}

func (x *MsgCreateDenom) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateDenom.ProtoReflect.Descriptor instead.
func (*MsgCreateDenom) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateDenom) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgCreateDenom) GetSubdenom() string {
	if x != nil {
		return x.Subdenom
	}
	return ""
}

type MsgCreateDenomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateDenomResponse) Reset() {
	*x = MsgCreateDenomResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateDenomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateDenomResponse) ProtoMessage() {}

func (x *MsgCreateDenomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateDenomResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateDenomResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateDenomResponse) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type MsgMint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	MintTo        string                 `protobuf:"bytes,3,opt,name=mint_to,json=mintTo,proto3" json:"mint_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMint) Reset() {
	*x = MsgMint{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMint) ProtoMessage() {}

func (x *MsgMint) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMint.ProtoReflect.Descriptor instead.
func (*MsgMint) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgMint) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgMint) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgMint) GetMintTo() string {
	if x != nil {
		return x.MintTo
	}
	return ""
}

type MsgMintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintResponse) Reset() {
	*x = MsgMintResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintResponse) ProtoMessage() {}

func (x *MsgMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintResponse.ProtoReflect.Descriptor instead.
func (*MsgMintResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgBurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurn) Reset() {
	*x = MsgBurn{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurn) ProtoMessage() {}

func (x *MsgBurn) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurn.ProtoReflect.Descriptor instead.
func (*MsgBurn) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgBurn) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgBurn) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgBurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurnResponse) Reset() {
	*x = MsgBurnResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurnResponse) ProtoMessage() {}

func (x *MsgBurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurnResponse.ProtoReflect.Descriptor instead.
func (*MsgBurnResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{5}
}

type MsgChangeAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	NewAdmin      string                 `protobuf:"bytes,3,opt,name=new_admin,json=newAdmin,proto3" json:"new_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgChangeAdmin) Reset() {
	*x = MsgChangeAdmin{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgChangeAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChangeAdmin) ProtoMessage() {}

func (x *MsgChangeAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChangeAdmin.ProtoReflect.Descriptor instead.
func (*MsgChangeAdmin) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgChangeAdmin) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgChangeAdmin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgChangeAdmin) GetNewAdmin() string {
	if x != nil {
		return x.NewAdmin
	}
	return ""
}

type MsgChangeAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgChangeAdminResponse) Reset() {
	*x = MsgChangeAdminResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgChangeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChangeAdminResponse) ProtoMessage() {}

func (x *MsgChangeAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChangeAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgChangeAdminResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{7}
}

type MsgForceTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DestAddr      string                 `protobuf:"bytes,3,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgForceTransfer) Reset() {
	*x = MsgForceTransfer{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgForceTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgForceTransfer) ProtoMessage() {}

func (x *MsgForceTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgForceTransfer.ProtoReflect.Descriptor instead.
func (*MsgForceTransfer) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgForceTransfer) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgForceTransfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgForceTransfer) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

type MsgForceTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgForceTransferResponse) Reset() {
	*x = MsgForceTransferResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgForceTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgForceTransferResponse) ProtoMessage() {}

func (x *MsgForceTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgForceTransferResponse.ProtoReflect.Descriptor instead.
func (*MsgForceTransferResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{9}
}

var File_heya_tokenfactory_v1_tx_proto protoreflect.FileDescriptor

const file_heya_tokenfactory_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1dheya/tokenfactory/v1/tx.proto\x12\x14heya.tokenfactory.v1\x1a\x17cosmos/msg/v1/msg.proto\"Q\n" +
	"\x0eMsgCreateDenom\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\bsubdenom\x18\x02 \x01(\tR\bsubdenom:\v\x82\xe7\xb0*\x06sender\".\n" +
	"\x16MsgCreateDenomResponse\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\"_\n" +
	"\aMsgMint\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x17\n" +
	"\amint_to\x18\x03 \x01(\tR\x06mintTo:\v\x82\xe7\xb0*\x06sender\"\x11\n" +
	"\x0fMsgMintResponse\"F\n" +
	"\aMsgBurn\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount:\v\x82\xe7\xb0*\x06sender\"\x11\n" +
	"\x0fMsgBurnResponse\"h\n" +
	"\x0eMsgChangeAdmin\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x1b\n" +
	"\tnew_admin\x18\x03 \x01(\tR\bnewAdmin:\v\x82\xe7\xb0*\x06sender\"\x18\n" +
	"\x16MsgChangeAdminResponse\"l\n" +
	"\x10MsgForceTransfer\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1b\n" +
	"\tdest_addr\x18\x03 \x01(\tR\bdestAddr:\v\x82\xe7\xb0*\x06sender\"\x1a\n" +
	"\x18MsgForceTransferResponseB\xbf\x01\n" +
	"\x18com.heya.tokenfactory.v1B\aTxProtoP\x01Z(heya/heya/tokenfactory/v1;tokenfactoryv1\xa2\x02\x03HTX\xaa\x02\x14Heya.Tokenfactory.V1\xca\x02\x14Heya\\Tokenfactory\\V1\xe2\x02 Heya\\Tokenfactory\\V1\\GPBMetadata\xea\x02\x16Heya::Tokenfactory::V1b\x06proto3"

var (
	file_heya_tokenfactory_v1_tx_proto_rawDescOnce sync.Once
	file_heya_tokenfactory_v1_tx_proto_rawDescData []byte
)

func file_heya_tokenfactory_v1_tx_proto_rawDescGZIP() []byte {
	file_heya_tokenfactory_v1_tx_proto_rawDescOnce.Do(func() {
		file_heya_tokenfactory_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_tx_proto_rawDesc), len(file_heya_tokenfactory_v1_tx_proto_rawDesc)))
	})
	return file_heya_tokenfactory_v1_tx_proto_rawDescData
}

var file_heya_tokenfactory_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_heya_tokenfactory_v1_tx_proto_goTypes = []any{
	(*MsgCreateDenom)(nil),           // 0: heya.tokenfactory.v1.MsgCreateDenom
	(*MsgCreateDenomResponse)(nil),   // 1: heya.tokenfactory.v1.MsgCreateDenomResponse
	(*MsgMint)(nil),                  // 2: heya.tokenfactory.v1.MsgMint
	(*MsgMintResponse)(nil),          // 3: heya.tokenfactory.v1.MsgMintResponse
	(*MsgBurn)(nil),                  // 4: heya.tokenfactory.v1.MsgBurn
	(*MsgBurnResponse)(nil),          // 5: heya.tokenfactory.v1.MsgBurnResponse
	(*MsgChangeAdmin)(nil),           // 6: heya.tokenfactory.v1.MsgChangeAdmin
	(*MsgChangeAdminResponse)(nil),   // 7: heya.tokenfactory.v1.MsgChangeAdminResponse
	(*MsgForceTransfer)(nil),         // 8: heya.tokenfactory.v1.MsgForceTransfer
	(*MsgForceTransferResponse)(nil), // 9: heya.tokenfactory.v1.MsgForceTransferResponse
}
var file_heya_tokenfactory_v1_tx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heya_tokenfactory_v1_tx_proto_init() }
func file_heya_tokenfactory_v1_tx_proto_init() {
	if File_heya_tokenfactory_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_tx_proto_rawDesc), len(file_heya_tokenfactory_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heya_tokenfactory_v1_tx_proto_goTypes,
		DependencyIndexes: file_heya_tokenfactory_v1_tx_proto_depIdxs,
		MessageInfos:      file_heya_tokenfactory_v1_tx_proto_msgTypes,
	}.Build()
	File_heya_tokenfactory_v1_tx_proto = out.File
	file_heya_tokenfactory_v1_tx_proto_goTypes = nil
	file_heya_tokenfactory_v1_tx_proto_depIdxs = nil
}
